name: Deploy to Github Pages
on:
    push:
        branches:
            - feature/usecallback

jobs:
    deploy:
        name: Deploy Application
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@master
            - name: Create Node Environment
              uses: actions/setup-node@v1
              with: 
                node-version: 16.x
            - name: Install Packages and Build Application
              run: |
                npm install -g @vue/cli yarn
                npm install
                npm build
            - name: Deploy
              uses: s0/Chandan9898Kumar/useCallback-memo@feature/usecallback
              env:
                REPO: self
                BRANCH: master
                FOLDER: dist
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}